services:
  #  mysql:
  #    image: mysql:8.0
  #    container_name: mysql
  #    cap_add:
  #      - SYS_NICE
  #    restart: always
  #    environment:
  #      - MYSQL_DATABASE=testdb
  #      - MYSQL_ROOT_PASSWORD=password
  #    ports:
  #      - '3306:3306'
  #    volumes:
  #      - mysql_data:/var/lib/mysql
  #      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  #    networks:
  #      - default
  #
  db-mysql:
    image: mysql:5.7.40
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: jobhunter
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    expose:
      - "3306"
    networks:
      - default

  backend-spring:
    container_name: backend-spring
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_DATABASE_HOST: host.docker.internal
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/jobhunter
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      LOGSTASH_HOST: host.docker.internal:5600
    networks:
      - default

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
    networks:
      - default

  elastic-search:
    image: elasticsearch:7.14.1
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      - default

  kibana:
    image: kibana:7.14.1
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200
    networks:
      - default

  logstash:
    image: logstash:7.14.1
    container_name: logstash
    restart: always
    ports:
      - "5600:5600" # Socket port
      - "5044:5044"
    #      - "9600:9600"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://elastic-search:9200
      - XPACK_MONITORING_ENABLED=true
    networks:
      - default

networks:
  default:
    name: backend-spring

